version: '3.7'
services:
  app:
    container_name: 'app'
    restart: always
    build: .
    ports:
      - "8000:8000"
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:8000 app:server
    working_dir: '/root'
    tty: true
    volumes:
      - ./src:/root/src/
      - ./zshrc:/root/.zshrc