#!/usr/bin/python

import pafy
import pandas as pd
from dateutil.parser import parse
from datetime import datetime
import xlrd
from pandas import ExcelWriter
from numbers import Number
import matplotlib.pyplot as plt

url_list = ['rymAn415IFc', 'm10NXanodz8', 'jESL86TFj48', 'fhVfKsOQe6k', 'H93JVcLns-M', '41YwoayGaOE', 'PUsFIY1fzec', 'rnPogip-SEY', 'TaIYstvFTNk', 'mWiovP79wyY', 'bapKDxdFn6c', '3nS0ZSyUOzs']
# url = "http://www.youtube.com/watch?v=fM9QlHNt8vQ"

# create a video instance

data = []
for url in url_list:
    video = pafy.new(url)
    data.append({'title': video.title, 'author': video.author, 'id': video.videoid, 'duration': video.duration,
    'rating': video.rating, 'views': video.viewcount, 'thumbnail': video.thumb, 'published date': video.published,
    'category': video.category, 'description': video.description, 'keywords': video.keywords
    })

df = pd.DataFrame(data)
print(df)
    
writer = ExcelWriter('youtubeChannelOutput.xlsx')
df.to_excel(writer,'youtubeOutput')
writer.save()

# need to define plotting settings
df['views'].plot(grid = True, figsize=(16, 10))


# get certain attributes

print("\n\n")
print("Title, Rating, Length...")
print("------------------------")
print(video.title)
print(video.rating)  # out of 5
print(video.length)  # seconds
print(video.viewcount)
print("\n")

# get video metadata

print("Video meta info...")
print("------------------")
print(video)
print("\n")




# show all formats for a video:

print("All available formats...")
print("------------------------")
streams = video.streams
print [(s.resolution, s.extension) for s in streams]
print("\n")

# show all formats and their download/stream url:

print("All available streams...")
print("------------------------")
for s in streams:
    print(s.resolution, s.extension, s.url)
print("\n")

# get best resolution regardless of file format

print("Best available quality...")
print("-------------------------")
best = video.getbest()
print(best.resolution, best.extension)
print("\n")

# get best resolution for a specified file format
# (mp4, webm, flv or 3gp)

print("Best available mp4 quality...")
print("-----------------------------")
best = video.getbest(preftype="mp4")
print(best.resolution, best.extension)
print("\n")

# get best resolution for specified file format, or return a different format
# if one happens to have a better resolution than the specified format

print("Best available quality, mp4 if exists as best")
print("---------------------------------------------")
best = video.getbest(preftype="mp4", ftypestrict=False)
print(best.resolution, best.extension)
print("\n")

# get url - for download or for streaming in mplayer / vlc

print("Best available quality url")
print("--------------------------")
print(best.url)
print("\n")

# download video, show progress

print("Download video, show progress")
print("-----------------------------")
print("Uncomment line in source file to enable")
#best.download(progress=True)
print("\n")

# download, specify output filepath

print("Download video, specify filepath")
print("--------------------------------")
print("Uncomment line in source file to enable")
#filename = "/tmp/" + best.title + best.extension
#best.download(progress=True, filepath=filename)