version: '3.7'
services:
  dash-app:
    restart: always
    build: .
    container_name: 'dash-app'
    ports:
      - "5050:5050"
    working_dir: '/root'
    tty: true
    volumes:
      - ./src:/root/src/
      - ./zshrc:/root/.zshrc